[package]
name = "test-spdk-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.147"
spdk-rs = { path = "/home/arc9693/spdk-rs" }
lazy_static = "1.4"
serde = "1.0"
serde_json = "1.0"
